#!/bin/bash

mkdir -p build/monado && \
cmake -Smonado -Bbuild/monado -DCMAKE_BUILD_TYPE=Debug -DXRT_FEATURE_SERVICE=OFF -DXRT_FEATURE_COMPOSITOR_MAIN=OFF -DXRT_FEATURE_OPENXR=OFF -DXRT_HAVE_WAYLAND=OFF -DXRT_HAVE_XLIB=OFF -DXRT_HAVE_XRANDR=OFF -DXRT_HAVE_XCB=OFF -DXRT_HAVE_OPENGL=OFF -DXRT_HAVE_OPENGLES=OFF -DXRT_HAVE_VULKAN=OFF -DXRT_HAVE_EGL=OFF -DXRT_HAVE_DBUS=OFF -DXRT_HAVE_JPEG=OFF -DXRT_HAVE_LIBUVC=OFF -DXRT_HAVE_OPENCV=OFF -DXRT_HAVE_FFMPEG=OFF -DXRT_FEATURE_STEAMVR_PLUGIN=OFF -DXRT_BUILD_DRIVER_HANDTRACKING=OFF -DXRT_BUILD_DRIVER_VF=OFF -DBUILD_TESTING=OFF -G Ninja && \
cmake --build build/monado


